steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: teched-us01
    integrationFlowId: I311241-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: teched-us01
    integrationFlowId: I311241-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: teched-us01
    integrationFlowId: I311241-flow4
    integrationFlowName: I311241-flow4
    packageId: CICD
    filePath: I311241-flow4.zip
    //pipeline steps configuration